# Generated by Django 4.2.7 on 2025-08-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipotratamento',
            name='tempo_medio_atendimento',
        ),
        migrations.AddField(
            model_name='campanhamarketing',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.clinica'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.clinica'),
        ),
        migrations.AddField(
            model_name='cupomdesconto',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.clinica'),
        ),
        migrations.AddField(
            model_name='lead',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.clinica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.clinica'),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.clinica'),
        ),
        migrations.AddField(
            model_name='tipotratamento',
            name='tempo_minimo_atendimento',
            field=models.PositiveIntegerField(default=30, help_text='Tempo mínimo de atendimento em minutos.'),
        ),
    ]
