# Generated by Django 4.2.7 on 2025-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_remove_tipotratamento_tempo_medio_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('ATENDENTE', 'Atendente'), ('PROFISSIONAL', 'Profissional da Saúde'), ('COORDENADOR', 'Coordenador')], max_length=20),
        ),
    ]
