# Generated by Django 4.2.7 on 2025-08-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_user_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('ATENDENTE', 'Atendente'), ('PROFISSIONAL', 'Profissional da Saúde'), ('COORDENADOR', 'Coordenador'), ('PACIENTE', 'Paciente')], max_length=20),
        ),
    ]
